### ISSUE TITLE
Make a change_type not bump the version?

### ISSUE THREAD

**Issue by FezVrasta** [RollingVersions/RollingVersions#230]
Hi, I was wondering if there's a way to define a `[[packages.change_types]]` entry that won't bump the version at all?

Would this work?

```
  tag_format = "v{{MAJOR}}.{{MINOR}}.{{PATCH}}{{?-{{HOTFIX}}}}"
  version_schema = ["MAJOR", "MINOR", "PATCH", "HOTFIX", "NONE"]

    [[packages.change_types]]
      id = "qa"
      bumps = "NONE"
      plural = "QAs"
```

**Comment by ForbesLindesay** [comment]
This isn’t supported, because we can’t do a release without bumping the version number. I don’t personally think it makes sense to track any changes that don’t even result in a release. If a change is largely internal but you want to add something to a release notes, I think it should be ok to bump the patch version.

**Comment by FezVrasta** [comment]
Makes sense, thanks!
